const x = [
  { side: "immune", num: 9,
    units: 608,
    hitPoints: 10288,
    damage: 76, damageType: "cold",  // 46208
    initiative: 18,
    weaknesses: ["bludgeoning"],
    immunities: ["cold"]
  },
  { side: "infection", num: 1,
    units: 103,
    hitPoints: 46709,
    damage: 66, damageType: "slashing",  // 6798
    initiative: 16,
  },
  { side: "infection", num: 3,
    units: 971,
    hitPoints: 33066,
    damage: 7, damageType: "slashing",
    initiative: 12,
    weaknesses: ["bludgeoning"],
  },
  { side: "infection", num: 5,
    units: 971,
    hitPoints: 28081,
    damage: 7, damageType: "bludgeoning",
    initiative: 11,
    weaknesses: ["fire", "slashing"],
  },
  { side: "infection", num: 6,
    units: 617,
    hitPoints: 41829,
    damage: 11, damageType: "bludgeoning",
    initiative: 20,
  },
  { side: "infection", num: 7,
    units: 56,
    hitPoints: 25050,
    damage: 120, damageType: "radiation",
    initiative: 2,
    weaknesses: ["fire"],
    immunities: ["radiation"]
  },
  { side: "infection", num: 8,
    units: 14,
    hitPoints: 42669,
    damage: 481, damageType: "fire",
    initiative: 13,
  },
  { side: "infection", num: 9,
    units: 522,
    hitPoints: 30426,
    damage: 13, damageType: "cold",
    initiative: 8,
    weaknesses: ["radiation"],
  }
]